### ISSUE TITLE
error in implementation

### ISSUE THREAD

**Issue by imadhaj** [okld/streamlit-gallery#2]
I run the code in my local and i have this error : 
```
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\AppData\Local\Programs\Python\Python39\Scripts\streamlit.exe\__main__.py", line 4, in <module>
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\streamlit\__init__.py", line 78, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\streamlit\delta_generator.py", line 19, in <module>
    from streamlit import caching
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\streamlit\caching.py", line 40, in <module>
    from streamlit.hashing import Context
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\streamlit\hashing.py", line 39, in <module>
    from streamlit.folder_black_list import FolderBlackList
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\streamlit\folder_black_list.py", line 39, in <module>
    if config.get_option("global.developmentMode"):
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\streamlit\config.py", line 86, in get_option
    parse_config_file()
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\streamlit\config.py", line 994, in parse_config_file
    _update_config_with_toml(file_contents, filename)
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\streamlit\config.py", line 915, in _update_config_with_toml
    _set_option(
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\streamlit\config.py", line 895, in _set_option
    assert key in _config_options, 'Key "%s" is not defined.' % key
AssertionError: Key "theme.base" is not defined.
```

**Comment by okld** [comment]
Hello @imadhaj,

Which version of Streamlit are you using?
